### ISSUE TITLE
an easy way do nuke a board if all else fails

### ISSUE THREAD

**Issue by lostfile1** [fgahr/termchan#7]
say if a board gets spammed to death may be a fail-safe command could delete all of the threads or a range of them without having to delete the database file of the board

**Comment by lostfile1** [comment]
heres my silly little script i wrote to quickly fix that

```
#!/bin/bash
echo "board nukeing script dont run this unless you really have to this deletes the database file"
read -p 'Board Name: ' boardvar
rm -f boards/$boardvar.db

```

**Comment by fgahr** [comment]
I don't think that should be integrated into termchan. That's easy enough to do with SQL either manually or with a small maintenance script if it turns into a regular occurence.
I think integrating that kind of functionality into termchan directly is rather pointless.
Communicating this (very specific) request to the server process would require another channel of communication which would incur quite a bit of overhead. It also seems very brittle.
The configuration and database is deliberately transparent and simple to allow interacting with it via other means.

Disabling a board altogether can be done by removing it from the config.json file and reloading (sending SIGHUP) or restarting termchan. I don't think the backend would be happy about a database file just disappearing. I never tested this but I assume it would keep responding with 500 error for that board afterwards.

I could see myself adding "disabled" and "locked" fields to the configuration for each board to disable it entirely or disable posting if you think that would solve it.

Note that if you run it as a proper service (with, say, systemd) you can configure it with a reload option to send the SIGHUP signal so you don't need to look up the process ID yourself. I do encourage testing of the reload functionatily as I haven't yet used it a lot myself :)

**Comment by lostfile1** [comment]
true

**Comment by fgahr** [comment]
If you don't mind, I will close this issue.

I have a few breaking changes in mind that should be beneficial to the project, but I won't have much time for the next 6-8 weeks anyway.
If you have questions, I'll be idle in ##termchan on freenode.  May not answer right away, permanent session (screen/tmux) recommended.
If you're interested in contributing, I can probably help you with that as well.
